"""Import models

Revision ID: 14f1108361ec
Revises: 
Create Date: 2026-01-08 10:18:50.236149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f1108361ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('surname', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phonenumber', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('licenseid', sa.String(length=120), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('priceperkm', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('licenseid'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phonenumber'),
    sa.UniqueConstraint('surname')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('representative', sa.String(length=80), nullable=False),
    sa.Column('mechanical_code', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mechanical_code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('passenger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('surname', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phonenumber', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phonenumber'),
    sa.UniqueConstraint('surname')
    )
    op.create_table('trip',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('vehicle',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('licence_plate', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=80), nullable=False),
    sa.Column('fuel', sa.String(length=80), nullable=False),
    sa.Column('seats_number', sa.Integer(), nullable=False),
    sa.Column('handicap_seats', sa.Integer(), nullable=False),
    sa.Column('cv', sa.Integer(), nullable=False),
    sa.Column('kw', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.PrimaryKeyConstraint('driver_id', 'licence_plate'),
    sa.UniqueConstraint('licence_plate')
    )
    op.create_table('trip_request',
    sa.Column('trip_code', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('pickup_point', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['passenger_id'], ['passenger.id'], ),
    sa.ForeignKeyConstraint(['trip_code'], ['trip.code'], ),
    sa.PrimaryKeyConstraint('trip_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_request')
    op.drop_table('vehicle')
    op.drop_table('trip')
    op.drop_table('passenger')
    op.drop_table('school')
    op.drop_table('driver')
    # ### end Alembic commands ###
